version: '3.8'

services:
  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html   # Map the root project folder to /var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  # PHP-FPM service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php
    volumes:
      - .:/var/www/html   # Map the root project folder to /var/www/html
    depends_on:
      - mysql
    networks:
      - laravel

  # MySQL 8 Service
  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root         # Set the root password for MySQL
      MYSQL_DATABASE: laravel_1         # Define the default database
    volumes:
      - ./mysql_data:/var/lib/mysql     # Persist the MySQL data
    ports:
      - "3307:3306"                     # Expose MySQL on port 3307 (local) to 3306 (inside the container)
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
